### ISSUE TITLE
Creators Update seems to have broken this. 

### ISSUE THREAD

**Issue by jeremymeyers** [pugwonk/wallpapr#1]
Crashes on launch. Here's the crash log thing:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at WallpaperFlickr.WallpaperFlickrSettings.ReadSettings()
   at WallpaperFlickr.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
Wallpapr
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Wallpapr/Wallpapr.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8922 (WinRelRS4.050727-8900)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by pugwonk** [comment]
Hey there - it looks a bit like you've got a corrupted settings files (installfolder\WallpaperFlickrSettings.xml). I think if you just delete that file and try running it again it might work?

**Comment by jeremymeyers** [comment]
Hmm... the only files in there are wallpapr.exe, flickrnet.dll and flickr.ico.

Possibly broken install, possibly because i put it in program files which requires admin to create files within... It was working until the creators update, i wonder if it moved the config file...

**Comment by pugwonk** [comment]
That's weird. If WallpaperFlickrSettings.xml doesn't exist, it uses defaults. If it exists, it tries to load it - it seems like yours exists and it's trying to load it, but is failing because it isn't a valid XML file. There's not some weird zero byte settings file in there somewhere or something?

**Comment by jeremymeyers** [comment]
not that i can see in explorer with hidden files shown

**Comment by jeremymeyers** [comment]
Just tried running as administrator and got the same error

**Comment by jeremymeyers** [comment]
Just as a clarification point: Hitting "Continue" instead of "Quit" enables it to work as normal. Additionally, i have Wallpapr set to load on startup which generates the error.  Quitting out of it and starting the app again does not generate the error. (I'm unsure as to whether this specifically points to it being in startup items as the issue vs it already have been loaded)

**Comment by pugwonk** [comment]
Fixed in https://github.com/pugwonk/wallpapr/commit/0addf2eeabc62644a6e6177dc97bbd931af0010d. I don't think this was to do with the Creators Update, but somehow you ended up with a corrupted settings file. It is now a bit more resilient in dealing with those.

**Comment by pugwonk** [comment]
(There's a new release page with a binary on it: https://github.com/pugwonk/wallpapr/releases)
